{{- if not .Values.appKeySecret.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferritecms.fullname" . }}
  labels:
    {{- include "ferritecms.labels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.appKeySecret.appKey | b64enc }}
{{- end }}