apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "synapse.fullname" . }}-media

spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass }}
  {{- end }}