apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "synapse.fullname" . }}-data

spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}